---
site_name: My Blog
site_description: This is my blog where I write about things I enjoy
site_url: https://www.my-awesome-blog.com
site_author: Brady Holt
google_analytics_id: UA-12345678-1
rss_path: rss.xml
sitemap_path: sitemap.xml

redirects:
  /2018/01/21/10-test-redirect.html: /test-redirect/
  /cron-expression-descriptor/: /cron-expression-descriptor-project/