---
title: My Blog
description: This is my blog where I write about things I enjoy
author: Brady Holt
url: https://www.my-awesome-blog.com
google_analytics_id: UA-12345678-1
rss_path: rss.xml
redirects:
  /2018/01/21/10-test-redirect.html: /test-redirect/