name: Publish to Registry

on:
  push:
    branches:
      - master
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: npm install
        run: npm install
      - name: npm publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_API_TOKEN
          npm publish
        env:
          CI: true
          NPM_API_TOKEN: ${{ secrets.NPM_API_TOKEN }}
