name: Publish to Registry

on:
  push:
    branches:
      - master
    paths:
      - '*'
      # Only if a file other than package.json was changed
      - '!package.json'
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1        
      - name: Use Node.js        
        uses: actions/setup-node@v1
        with:
          node-version: 8        
      - name: npm install      
        run: npm install
      - name: npm version        
        run: |
          git config user.name "Brady Holt"
          git config user.email "brady.holt@gmail.com"          
          npm version minor --force -m "Version %s"
          git push origin HEAD:master --tags
        env:
          CI: true
          NPM_API_TOKEN: ${{ secrets.NPM_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm publish        
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_API_TOKEN
          npm publish
        env:
          CI: true
          NPM_API_TOKEN: ${{ secrets.NPM_API_TOKEN }}          
        
